//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetDbTest
{
    using System;
    
    public partial class GetJobNumbersResult
    {
        public int Id { get; internal set; }
        public Nullable<int> Job_No__JOB_ { get; set; }
    }
}
