//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetDbTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InteracctDataContext : DbContext
    {
        public InteracctDataContext()
            : base("name=InteracctDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetJobNumbersResult> GetJobNumbers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetJobNumbersResult>("GetJobNumbers");
        }
    
        public virtual ObjectResult<GetActivitiesResult> GetActivities(Nullable<int> jobNumber, string package)
        {
            var jobNumberParameter = jobNumber.HasValue ?
                new ObjectParameter("JobNumber", jobNumber) :
                new ObjectParameter("JobNumber", typeof(int));
    
            var packageParameter = package != null ?
                new ObjectParameter("Package", package) :
                new ObjectParameter("Package", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActivitiesResult>("GetActivities", jobNumberParameter, packageParameter);
        }
    
        public virtual ObjectResult<GetPackagesResult> GetPackages(Nullable<int> jobNumber)
        {
            var jobNumberParameter = jobNumber.HasValue ?
                new ObjectParameter("JobNumber", jobNumber) :
                new ObjectParameter("JobNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPackagesResult>("GetPackages", jobNumberParameter);
        }
    }
}
